version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["**/Dockerfile"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 100
  runtime_version = "3.x.x"
