repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
    -   id: isort