repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/PyCQA/isort
    rev: master
    hooks:
    -   id: isort