language: python
python:
  - "3.8"

git:
  submodules: false

install:
  - python -m pip install poetry
  - poetry install

script:
  - poetry run black --check ./ferry
  - poetry run isort --check-only --diff --recursive ferry
