[tool.poetry]
name = "ferry"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
# General
python = "^3.8"
requests = "^2.23.0"
tqdm = "^4.46.1"

# Crawling
unidecode = "^1.1.1"
python-dateutil = "^2.8.1"
lxml = "^4.5.1"
ujson = "^4.0.1"
diskcache = "^4.1.0"
beautifulsoup4 = "^4.9.1"

# Database
SQLAlchemy = "^1.3.17"
sqlalchemy_mixins = "^1.2.1"
textdistance = "^4.2.0"
psycopg2 = "^2.8.5"
pandas = "^1.1.2"
networkx = "^2.5"

# NLP
nltk = "^3.5"
spacy = "^2.3.2"
fasttext = "^0.9.2"
tables = "^3.6.1"
en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz" } # the English language model for SpaCy
vaderSentiment = "^3.3.2"
pandarallel = "^1.5.1"
gensim = "^3.8.3"
edlib = "^1.3.8"
stackprinter = "^0.2.5"
numpy = "^1.23.2"
tabula-py = "^2.2.0"
click = "^7.1.2"
tika = "^1.24"
annoy = "^1.17.0"
sentry-sdk = "^1.4.3"

[tool.poetry.dev-dependencies]
eralchemy = "^1.2.10"
pylint = "^2.5.3"
black = "^20.8b1"
isort = "^5.6.4"
poetry-githooks = "^1.1.2"
plotly = "^4.11.0"
sqlalchemy-stubs = "^0.3"
ipython = "^7.18.1"
memory-profiler = "^0.58.0"
matplotlib = "^3.3.2"
mypy = "^0.790"
data-science-types = "^0.2.20"
stackprinter = "^0.2.5"
umap-learn = "^0.5.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.githooks]
pre-commit = "poetry run black ./ferry && poetry run isort ./ferry && poetry run pylint -j 0 ./ferry"

[build-system]
requires = ["poetry>=1.1.3"]
build-backend = "poetry.masonry.api"
