# See: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# TODO: migrate setup.py

[tool.black]
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#labels-line-length
line-length = 88
target-version = ["py312"]

[tool.pyright]
include = ["."]
exclude = ["legacy"]
# TODO: use strict
typeCheckingMode = "standard"

pythonVersion = "3.12"
pythonPlatform = "Linux"

reportImplicitOverride = true
reportImplicitStringConcatenation = true
reportMissingSuperCall = true
reportPropertyTypeMismatch = true
reportShadowedImports = true
reportUnnecessaryTypeIgnoreComment = true

# TODO
reportUnknownArgumentType = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
