[tool.poetry]
name = "ferry"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
tqdm = "^4.46.1"
unidecode = "^1.1.1"
python-dateutil = "^2.8.1"
lxml = "^4.5.1"
ujson = "^3.0.0"
PyMySQL = "^0.9.3"
diskcache = "^4.1.0"
SQLAlchemy = "^1.3.17"
sqlalchemy_mixins = "^1.2.1"
fastapi = "^0.56.0"
uvicorn = "^0.11.5"
textdistance = "^4.2.0"
beautifulsoup4 = "^4.9.1"
pydrive = "^1.3.1"
psycopg2 = "^2.8.5"

[tool.poetry.dev-dependencies]
eralchemy = "^1.2.10"
pylint = "^2.5.3"
black = "^19.10b0"
isort = {extras = ["pyproject"], version = "^4.3.21"}

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_first_party = "ferry"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
