ALTER TABLE courses
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE listings
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE flags
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE course_flags
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE professors
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE course_professors
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE buildings
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE locations
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;

ALTER TABLE course_meetings
ADD COLUMN time_added TIMESTAMP DEFAULT NULL,
ADD COLUMN last_updated TIMESTAMP DEFAULT NULL;
