# DEV CONFIG
# This configuration is used to only fetch course data (no evaluations) for the last 3 seasons in a dev environment. Please combine with -s option to specify exact seasons to fetch. For debug printing, use -d option.

cas_cookie: null
database_connect_string: null
fetch_classes: true
fetch_evals: true
parse_evals: false
generate_diagram: false
release: false
sentry_url: null
sync_db: false
use_cache: true
seasons:
  - LATEST_4
