# DEV CONFIG
# This configuration is used to only fetch course data (no evaluations) for the last 3 seasons in a dev environment. Please combine with -s option to specify exact seasons to fetch. For debug printing, use -d option.

release: false
seasons:
  - LATEST_4
use_cache: true

crawl_seasons: true
crawl_classes: true
