# PROD CONFIG
# This configuration is used for fetching the latest data for the listed seasons of course data (no evaluations).

# Sentry URL & DB URL are passed through env
release: true
seasons: [ '202601', '202602', '202603', '202701' ]

crawl_seasons: true
crawl_classes: true
