# PROD CONFIG
# This configuation is used for syncing the last 3 seasons of course data (no evaluations) to the production database.

cas_cookie: null
database_connect_string: null
fetch_evals: false
generate_diagram: false
release: true
seasons:
- LATEST_3
sentry_url: null
sync_db: true
