# PROD CONFIG
# This configuration is used for fetching the latest data for the last 3 seasons of course data (no evaluations).

# Sentry URL & DB URL are passed through env
release: true
seasons:
  - LATEST_4

crawl_seasons: true
crawl_classes: true
