# PROD CONFIG
# This configuation is used for fetching the latest data for the last 3 seasons of course data (no evaluations).

cas_cookie: null
database_connect_string: null
fetch_classes: true
fetch_evals: false
parse_evals: false
generate_diagram: false
release: true
seasons:
- LATEST_3
sentry_url: null
sync_db: false
