# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: sudo apt-get install python3.8-dev graphviz libgraphviz-dev pkg-config
    - name: Install Python dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Lint with black
      run: |
        poetry run black --check ferry
    - name: Lint with isort
      run: |
        poetry run isort --check-only -diff --recursive ferry
