name: See New Course Titles

on:
  workflow_run:
    workflows: ["Ferry Run"]
    types:
      - completed
  workflow_dispatch:

jobs:
  extract-courses:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout ferry-data
        uses: actions/checkout@v2
        with:
          repository: coursetable/ferry-data
          token: ${{ secrets.TOKEN_FOR_FERRY_DATA }}
          path: ferry-data
          fetch-depth: 1  # Fetches only the last commit


      - name: Fetch the latest commit SHA from ferry-data
        if: github.event_name == 'workflow_run'
        id: get-latest-commit
        run: echo "LATEST_COMMIT_SHA=$(git log -1 --format=%H)" >> $GITHUB_ENV
        working-directory: ./ferry-data

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to extract new courses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ env.LATEST_COMMIT_SHA }}
        run: python ./ferry-data/.github/scripts/get_course_names.py

      - name: Output new courses
        run: cat new_courses.txt
